source ~/.bash/aliases
source ~/.bash/colors
source ~/.bash/completion
source ~/.bash/env
source ~/.bash/functions
source ~/.bash/path

if [[ -s ~/.rvm/scripts/rvm ]]
then
  source ~/.rvm/scripts/rvm
fi

source ~/.bash/prompt

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
