if [ -f ~/.bashrc ]; then
  source ~/.bashrc
fi

##
# Your previous /Users/ludo/.bash_profile file was backed up as /Users/ludo/.bash_profile.macports-saved_2011-07-24_at_14:21:19
##

# MacPorts Installer addition on 2011-07-24_at_14:21:19: adding an appropriate PATH variable for use with MacPorts.
export PATH=/opt/local/bin:/opt/local/sbin:$PATH
# Finished adapting your PATH environment variable for use with MacPorts.

