source ~/baggage/dotfiles/bash/aliases
source ~/baggage/dotfiles/bash/colors
source ~/baggage/dotfiles/bash/completion
source ~/baggage/dotfiles/bash/env
source ~/baggage/dotfiles/bash/functions
source ~/baggage/dotfiles/bash/path

if [[ -s ~/.rvm/scripts/rvm ]]
then
  source ~/.rvm/scripts/rvm
fi

source ~/baggage/dotfiles/bash/prompt