" Pathogen ********************************************************************
call pathogen#runtime_append_all_bundles() 
call pathogen#helptags()

" Colors **********************************************************************
let &t_Co=256 " 256 colors
syntax enable
set background=dark

let g:solarized_termcolors=256
colorscheme solarized

" Misc settings ***************************************************************
set number " Show line numbers
